version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: avail_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: avail_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  api:
    build: ./packages/api
    container_name: avail_api
    env_file: .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  worker:
    build: ./packages/worker
    container_name: avail_worker
    env_file: .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - RPC_ENDPOINT=${RPC_ENDPOINT}
      - CRON=${CRON}
    depends_on:
      - mongo

volumes:
  mongo_data:
